### ISSUE TITLE
Problem compiling with gromacs-5.1.2

### ISSUE THREAD

**Issue by fifthguy** [RashmiKumari/g_mmpbsa#5]
Hello!

Firstly thank you for the effort of developing the tool, it's awesome!

I first tested the version from the binary download - which works perfectly, I then wanted to compile (to get a better performance and so on and got a an error during configuration - saying that the gromacs libgmx was not found. 

I use gromacs-5.1.2 installed to its default location (/usr/local/gromacs), during g_mmpbsa configuration I set the PATH_TO_GROMACS flag (however it actually writes) to my gromacs install location; I also tried providing the path to the actual libgmx* files (in /usr/lib) in addition to the first path, i tried exporting the relevant paths (export <RELEVANT_PATHS> (in accordance to the installation guide you provide). Still I'm getting the same error.

Have you faced this kind of issue before, did you already start working on a solution?

Apparently the configuration (the cmake scripts) search for a libgmx folder, which is not present in gmx-5.1.2 - does this conclusion make sense?

Do you have any ideas, how to fix it? What does it actually need from it? Can I feed him the directory in another fashion (within the cmake) or would I have to rewrite large sections?

Thanks again!
Sincerely, 

tomaz

**Comment by fifthguy** [comment]
Hello again,

should there be any issues if I for example do a separate installation of gomacs-5.0.x, compile g_mmpbsa with that and then use the trajectories from my gmx-5.1.x simulation? Would this be a plausible solution? The gmx data files (tpr, trr, xtc) should be compatible between versions or am I mistaken?

the main aim of compiling it myself also constitutes of the idea of adding some atom/ion parameters to the code and/or modifying it a bit... From what I noticed the atom radii are defined statically in the code (radius.c), would it make sense to have a separate input  file with additional necessary parameters to suit the needs of less general cases?

Thank you again again,

T

**Comment by rjdkmr** [comment]
Hi,

If Gromacs is installed in standard location, you need not to give path to Gromacs installation directory. cmake should find it. libgmx is a library of previous Gromacs versions (4.0/4.5/4.6). From 5.0 version, library name is libgromacs. So in this case, when libgmx is not found, cmake tries to search for libgromacs.

It appears that cmake is not able to find libgromacs library. What is your cmake command and its output? Also where is libgromacs.a(.so) on your system?

You can read xtc, which is generated from any version of Gromacs, however, you cannot read tpr because it is version dependent.

Yes, atomic radii are statically defined and radii is assigned using the atom type (not atom name). You may change radius.c to include new atom-type and respective radius. I agree, it is good idea to read radii from separate input file. We will look into it.

With best regards,
 Rajendra

**Comment by fifthguy** [comment]
Hello!

**COMMAND**
 cmake -DAPBS14=om -DCMAKE_INSTALL_PREFIX=/opt/g_mmpbsa -
**MESSAGE**
DGMX_PATH=/usr/local/gromacs ..
-- checking for module 'libgromacs'
--   package 'libgromacs' not found
-- Could NOT find GROMACS (missing:  GROMACS_LIBRARY GROMACS_INCLUDE_DIR) 
-- Continue checking for other Gromacs version library file
-- checking for module 'libgmx'
--   package 'libgmx' not found
-- Could NOT find GROMACS (missing:  GROMACS_LIBRARY GROMACS_INCLUDE_DIR) 
CMake Error at src/CMakeLists.txt:72 (message):
  

  Gromacs path is not defined.....

  USE:

   -DGMX_PATH=/path/to/gromacs
    or  
   export CMAKE_PREFIX_PATH="/path/to/gromacs"



-- Configuring incomplete, errors occurred!
See also "/home/kemal/mmpbsa/g_mmpbsa/build/CMakeFiles/CMakeOutput.log".


**libgromacs location**
/usr/local/gromacs/lib/x86_64-linux-gnu

however, the lib-file is not called merely libgromacs but libgromacs_mpi..., in the folder there are two symlinks they both point to a file called libgromacs_mpi.so.1.2.0, in a transitive matter A->B->libgromacs_mpi.so.1.2.0. In the DIagram above A stands for libgromacs_mpi.so.
=================================================================



Thanks again, T

**Comment by rjdkmr** [comment]
Hi,

g_mmpbsa cannot be compiled with Gromacs-MPI. Please use Gromacs without MPI for compilation. 

With best regards,
Rajendra

**Comment by fifthguy** [comment]
Hi,

thanks, compilation works now! I do have another (probably stupid) question for you however: The code should still read & process simulation trajectories correctly, even if those were produced by an MPI-version of GMX?

T

**Comment by rjdkmr** [comment]
xtc/tpr/ndx files are always same whether generated from Gromacs-MPI or without MPI.

**Comment by cloudella48** [comment]
HI there! 
I am facing a similar problem right now, the gromacs libgromacs or libgmx are not found and I do not know what I shall do about it. 
![image](https://user-images.githubusercontent.com/117277524/223659749-3b0809ae-061d-46aa-aa91-0049712ca7d8.png)
would be great if you could help me !

**Comment by youssif2002** [comment]
> HI there! I am facing a similar problem right now, the gromacs libgromacs or libgmx are not found and I do not know what I shall do about it. ![image](https://user-images.githubusercontent.com/117277524/223659749-3b0809ae-061d-46aa-aa91-0049712ca7d8.png) would be great if you could help me !

have you solved it yet?

**Comment by cloudella48** [comment]
Hi there :) 

I did not really solve the problem, but I figured out, that it is due to the GROMACS version I am using. This tool can only be used with older versions of the GROMACS package. As this dox3dna tool is only supported until 2018, newer GROMACS versions do not fit with t apparently. Anyhow, I did not figure out how to download an older version of GROMACS because due to something this is not possible. If you find a solution to this issue, please let me know ! 

best, 
Anne
