### ISSUE TITLE
VdW/Elec for Protein and Ligand is 0 in Vacuum MM energy - in the tutorial

### ISSUE THREAD

**Issue by bieniekmateusz** [RashmiKumari/g_mmpbsa#9]
I downloaded your tutorial from here: https://rashmikumari.github.io/g_mmpbsa/single_protein_ligand_binding_energy.html

Regardless of whether MM is computed separately or together with PBSA, these terms are always 0. Here is the energy_MM.xvg attached: [mm.zip](https://github.com/RashmiKumari/g_mmpbsa/files/1532386/mm.zip)

My GMXLIB points at my 5.1.4 gromacs top directory but this has not changed anything. 

At the same time, the python script MmPbSaStat.py uses the columns:
`Energy = mmEn[5][i] - (mmEn[1][i] + mmEn[3][i])`
`Vdw.append(Energy)`

The original MMPBSA shows that there is a different potential energy betweenthe protein+ligand and the complex. 

Am I doing something wrong or is this a very serious issue?

**Comment by bieniekmateusz** [comment]
I've rerun the example with -incl_14 option which fills in all the details for the Vaccum MM Energy and what I get is this:
          0.000      -2673.714     -11236.322         41.672         19.613      -2953.187     -11363.859       -468.295

With the binding energy MM contribution  being -468.295 = -2953.187+-11363.859 - ( -2673.714+-11236.322 + 41.672+19.613 )

Whereas without the -incl_14 option we get this:
          0.000          0.000          0.000          0.000          0.000       -321.145       -147.150       -468.295

So -incl_14 is calculated, as it should be, but is not written to the file. I think this is unnecessarily confusing. Not only these values are not written despite being calculated, but the analysis script MmPbSaStat.py still performs the addition on the empty columns pretending to be doing the actual calculation, which was already carried out by the original g_mmpbsa binary file.

**Comment by rjdkmr** [comment]
You have already found that -incl_14 option calculates all energies separately. However, without -incl_14 option, interaction energy is directly calculated, that's why other energies are zero. 

You may have noticed that calculating energy with -incl_14 is slower because each energy is calculated separately. Also, at the beginning, 1-4 atom pair list is generated that may take very long time. To speed up the calculation, interaction energy between two atom-groups are directly calculated when -incl_14 option is not used. g_mmpbsa does not calculate all energy in details when used without -incl_14. It does not affect the final result as you can see in your result.

MmPbSaStat.py is written in such a way that it can produce correct results with or without -incl_14 option.
